### ISSUE TITLE
Update tzdata to v. 1.1.2

### ISSUE THREAD

**Issue by jsmueller7** [Logflare/logflare#2206]
I've just been testing and I am seeing this error:

```
supabase-analytics 12:45:13.852 [error] GenServer :tzdata_release_updater terminating
supabase-analytics ** (ArgumentError) errors were found at the given arguments:
supabase-analytics 
supabase-analytics   * 2nd argument: not a tuple
supabase-analytics 
supabase-analytics     :erlang.element(1, :error)
supabase-analytics     (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
supabase-analytics     (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
supabase-analytics     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
supabase-analytics     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
supabase-analytics     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
supabase-analytics     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
supabase-analytics     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
supabase-analytics Last message: :check_if_time_to_update
supabase-analytics 
```

For me it looks like it's related to this issue: https://github.com/lau/tzdata/issues/148

You might consider to update `tzdata` to v. `1.1.2`.

**Comment by Ziinc** [comment]
Thanks for the report, yea we'll get to this before year ends. Thanks!
